// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vitrina.Data.Context;

#nullable disable

namespace Vitrina.Data.Migrations
{
    [DbContext(typeof(VitrinaDbContext))]
    partial class VitrinaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vitrina.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Audio",
                            CreatedAt = new DateTime(2025, 1, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium over-ear headphones with active noise cancellation and all-day battery life.",
                            ImageUrl = "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
                            IsActive = true,
                            Name = "Wireless Noise-Canceling Headphones",
                            Price = 249.99m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 2,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 1, 12, 10, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Slim 15.6-inch USB-C portable monitor for working on the go.",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80",
                            IsActive = true,
                            Name = "4K Portable Monitor",
                            Price = 329.00m,
                            Stock = 18
                        },
                        new
                        {
                            Id = 3,
                            Category = "Computing",
                            CreatedAt = new DateTime(2025, 1, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Compact mechanical keyboard with hot-swappable switches and RGB backlight.",
                            ImageUrl = "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=1200&q=80",
                            IsActive = true,
                            Name = "Mechanical Keyboard",
                            Price = 129.50m,
                            Stock = 42
                        },
                        new
                        {
                            Id = 4,
                            Category = "Wearables",
                            CreatedAt = new DateTime(2025, 2, 1, 8, 15, 0, 0, DateTimeKind.Utc),
                            Description = "Health-focused smartwatch with heart rate tracking, GPS, and sleep analytics.",
                            ImageUrl = "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
                            IsActive = true,
                            Name = "Smart Fitness Watch",
                            Price = 199.99m,
                            Stock = 27
                        },
                        new
                        {
                            Id = 5,
                            Category = "Office",
                            CreatedAt = new DateTime(2025, 2, 10, 11, 45, 0, 0, DateTimeKind.Utc),
                            Description = "Adjustable office chair with lumbar support and breathable mesh back.",
                            ImageUrl = "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
                            IsActive = true,
                            Name = "Ergonomic Office Chair",
                            Price = 289.00m,
                            Stock = 12
                        },
                        new
                        {
                            Id = 6,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 2, 18, 16, 20, 0, 0, DateTimeKind.Utc),
                            Description = "Fast charging stand compatible with modern phones and earbuds cases.",
                            ImageUrl = "https://images.unsplash.com/photo-1612817159949-3f7d9b07c9c6?auto=format&fit=crop&w=1200&q=80",
                            IsActive = true,
                            Name = "Wireless Charging Stand",
                            Price = 39.90m,
                            Stock = 65
                        },
                        new
                        {
                            Id = 7,
                            Category = "Computing",
                            CreatedAt = new DateTime(2025, 3, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Multi-port docking station with HDMI, Ethernet, and card reader support.",
                            ImageUrl = "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
                            IsActive = true,
                            Name = "USB-C Docking Station",
                            Price = 149.95m,
                            Stock = 21
                        },
                        new
                        {
                            Id = 8,
                            Category = "Audio",
                            CreatedAt = new DateTime(2025, 3, 14, 13, 30, 0, 0, DateTimeKind.Utc),
                            Description = "Portable speaker with balanced sound, water resistance, and 20-hour battery.",
                            ImageUrl = "https://images.unsplash.com/photo-1518441902117-f0a6a3f0d5b2?auto=format&fit=crop&w=1200&q=80",
                            IsActive = true,
                            Name = "Bluetooth Speaker",
                            Price = 89.99m,
                            Stock = 54
                        },
                        new
                        {
                            Id = 9,
                            Category = "Office",
                            CreatedAt = new DateTime(2025, 4, 1, 9, 40, 0, 0, DateTimeKind.Utc),
                            Description = "LED desk lamp with adjustable brightness and built-in USB charging port.",
                            ImageUrl = "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
                            IsActive = true,
                            Name = "Desk Lamp with USB Port",
                            Price = 54.75m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 10,
                            Category = "Computing",
                            CreatedAt = new DateTime(2025, 4, 12, 15, 0, 0, 0, DateTimeKind.Utc),
                            Description = "High precision gaming mouse with programmable buttons and low-latency sensor.",
                            ImageUrl = "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=1200&q=80",
                            IsActive = true,
                            Name = "Gaming Mouse",
                            Price = 74.25m,
                            Stock = 48
                        });
                });

            modelBuilder.Entity("Vitrina.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", "dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@vitrina.dev",
                            Name = "Admin User",
                            PasswordHash = "PBKDF2$100000$M2sLSVWCKjmNAWrhiLff2Q==$c3UWlPye+02m+RWkGYCP9nqGU1Cmb5MpNm1D23KpqK8=",
                            Role = (byte)1,
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 8, 5, 0, 0, DateTimeKind.Utc),
                            Email = "user@vitrina.dev",
                            Name = "Regular User",
                            PasswordHash = "PBKDF2$100000$yy8A999moS2/LzRxBqAfZQ==$uOMR3XbgOSu80whbJREikbZrV+3g6HfN1OsY0p1RsLo=",
                            Role = (byte)2,
                            Username = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
